version: '3.7'

services:
  bloomsky:
    image: patrickalin/docker-bloomsky
    container_name: bloomsky
    ports:
     - "1111:1111"
    volumes:
     - ./config.yaml:/config.yaml
    environment:
     - bloomskyAccessToken=${bloomskyAccessToken}
    labels:
     - traefik.port=1111
     - traefik.frontend.rule=Host:bloomsky.services.alin.be
     - traefik.frontend.entryPoints=http,https
     - traefik.backend=bloomsky
    networks:
     - traefik-net

networks:
  traefik-net:
    external: true
