version: '3.2'

services:
  bloomsky:
    image: patrickalin/docker-bloomsky
    container_name: bloomsky
    ports:
     - "1111:1111"
     - "1112:1112"
    volumes:
     - ./config.yaml:/config.yaml
    environment:
     - bloomskyAccessToken=${bloomskyAccessToken}
    labels:
     - traefik.port=1112
     - traefik.frontend.rule=Host:bloomsky.services.alin.be
     - traefik.frontend.entryPoints=https,http
     - traefik.backend=bloomsky
    networks:
     - web

networks:
  web:
    external:
      name: traefik_webgateway
